# Generated by Django 6.0.7 on 2026-08-13 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rms', '0002_alter_ordermenu_menu_alter_ordermenu_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidx', models.CharField(max_length=25, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=15)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='rms.order')),
            ],
        ),
    ]
