# Generated by Django 6.0.7 on 2026-08-11 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='rms.menu'),
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='rms.order'),
        ),
    ]
